[package]
name = "pombase_rc_string"
version = "0.1.0"
authors = ["Kim Rutherford <kmr@aska.gen.nz>"]

[dependencies]
lazy_static = "1.1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
weak-table = "0.2.3"
